# Generated by Django 3.2.11 on 2022-01-12 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guess', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='date',
            new_name='last_played_date',
        ),
    ]
