# Generated by Django 3.2.11 on 2022-01-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guess', '0002_rename_date_game_last_played_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='correct_number',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
